camera:
  id: 0
  width: 640      
  height: 480     
  fps: 30

detection:
  surface_min_bouteille: 5000 
  
  noyau_flou: 5

positionnement:
  buse_x: 640     
  tolerence: 40   # Double the tolerance since pixels are smaller

remplissage:
  seuil_plein_pourcentage: 90
  ip_adress: "192.168.1.10"
  port: 4840
  seuil_liquide: 40

plc:
  ip_adress: "192.168.1.10"
  port: 4840
