camera:
  id: 0
  width: 640
  height: 480
  fps: 30

detection:
  surface_min_bouteille: 10000

vision:
  crop_x_start: 250
  crop_x_end: 450

remplissage:
  seuil_plein_pourcentage: 90

plc:
  ip_adress: "192.168.1.10"
  port: 4840
